version: 2
before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env: ["CGO_ENABLED=0"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: ["-trimpath"]
    targets: ["go_first_class"]

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Bug fixes"
      regexp: "^.*bug[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      windows: windows
      linux: linux

    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: ItzDabbzz
    name: GoMCTools
  footer: |

    ---
    Made With 🖤 by ItzDabbzz
    ---


    _Released with [GoReleaser](https://goreleaser.com)!_