# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
archives:
  - format_overrides:
      - formats: zip
        goos: windows
    formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}

before:
  hooks:
    - go mod tidy


builds:
  - env: ["CGO_ENABLED=0"]
    flags: ["-trimpath"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets: ["go_first_class"]

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - order: 0
      regexp: '^.*feat(\([\w\-]+\))?:+.*$'
      title: "🚀 New Features"

    - order: 10
      regexp: '^.*(fix|bug)(\([\w\-]+\))?:+.*$'
      title: "🐛 Bug Fixes"

    - order: 20
      regexp: '^.*perf(\([\w\-]+\))?:+.*$'
      title: "⚡ Performance"

    - order: 30
      regexp: '^.*refactor(\([\w\-]+\))?:+.*$'
      title: "♻️ Refactoring"

    - order: 40
      regexp: '^.*(chore|build|ci)(\([\w\-]+\))?:+.*$'
      title: "🧰 Maintenance"

    - order: 50
      regexp: '^.*(deps|dep)(\([\w\-]+\))?:+.*$'
      title: "📦 Dependencies"

    - order: 999
      title: "Other work"
  sort: asc
  use: github

checksum:
  name_template: "checksums.txt"

gomod:
  proxy: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

project_name: GoMCTools

release:
  footer: |

    ---
    Made With 🖤 by ItzDabbzz
    ---


    _Released with [GoReleaser](https://goreleaser.com)!_
  github:
    name: GoMCTools
    owner: ItzDabbzz

version: 2