name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.8'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Run Linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          # Optionally add: skip-cache: true if you run into caching issues


